apiVersion: v1
entries:
  kato:
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2026-06-18T18:10:18.519178+07:00"
    description: Kubernetes troubleshooting via declarative UseCase flows with AI
      summaries
    digest: e45aba4c8c49e46dd39327adc2348b39509652b63404bc40f748e03ae45e7c40
    name: kato
    type: application
    urls:
    - kato-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2026-06-18T18:10:18.518992+07:00"
    description: Kubernetes troubleshooting via declarative UseCase flows with AI
      summaries
    digest: cfd4d7e8b2af80a3259c53aa319e132f0dc5a1754a3982a913b7a2f2032760da
    name: kato
    type: application
    urls:
    - kato-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-06-18T18:10:18.518528+07:00"
    description: Kubernetes troubleshooting via declarative UseCase flows with AI
      summaries
    digest: 0e7fbfb4aa927bfc411ac1ca18c648b688daef76be7099ff620a1899371597ab
    name: kato
    type: application
    urls:
    - kato-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-18T18:10:18.516952+07:00"
